name: pre-commit

on: [ pull_request ]

jobs:
  'pre-commit':
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # note: we use depth:0 so we can use

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run --files .pre-commit-config.yaml

      - name: analyze code with pre-commit
        run: 'pre-commit run --from-ref "origin/${{ github.base_ref }}" --to-ref HEAD'
